services:
  - type: web
    name: eas-tuition-next
    runtime: node
    rootDir: ./kr-unituition-next
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eas-db
          property: connectionString

databases:
  - name: eas-db
    plan: free
