import os
import re
import json
import pandas as pd

# Load universities.js
with open("d:/EASS/src/data/universities.js", "r", encoding="utf-8") as f:
    js_content = f.read()

# Extract the JSON array
match = re.search(r'export const universities = (\[.*\]);', js_content, re.DOTALL)
if not match:
    print("Failed to find universities array in universities.js")
    exit(1)

# Clean and load as json
js_str = match.group(1)
# Simple cleanup: replace single quotes or JS syntax if needed, but since it was generated by JSON.stringify earlier, it should be valid JSON
try:
    universities = json.loads(js_str)
except Exception as e:
    # Fallback: evaluate using JS and write to temp file
    print("JSON load failed, we will use a node script to output json first.")
    exit(1)

print(f"Loaded {len(universities)} universities from JS.")

def normalize_name(name):
    if not name or not isinstance(name, str):
        return ""
    # Remove newlines, parens, and their content
    name = re.sub(r'\(.*?\)', '', name)
    name = re.sub(r'\n', ' ', name)
    name = name.lower()
    # Remove "đại học", "cao đẳng", "trường"
    name = name.replace("đại học", "").replace("cao đẳng", "").replace("trường", "")
    name = name.replace("university", "").replace("college", "")
    name = re.sub(r'\s+', ' ', name).strip()
    return name

# Test matching for each file
files = {
    "TO2%.xlsx": "Sheet1",
    "TOP1%.xlsx": "Sheet1",
    "top3.xlsx": "Sheet1",
    "TruongNoTOPIK.xlsx": "Sheet1",
    "danhsachtruonghanche.xlsx": "Sheet1"
}

for name, sheet in files.items():
    path = os.path.join("d:/EASS", name)
    if not os.path.exists(path):
        print(f"File not found: {path}")
        continue
        
    df = pd.read_excel(path, sheet_name=sheet)
    
    # Identify school name column
    name_col = None
    for col in df.columns:
        # Check first 5 rows to see if they contain school names
        sample_vals = df[col].dropna().astype(str).tolist()[:5]
        if any("Đại học" in val or "Cao đẳng" in val or "snu" in val.lower() or "yonsei" in val.lower() for val in sample_vals):
            name_col = col
            break
            
    if name_col is None:
        # Fallback to column name checks
        for col in df.columns:
            c_lower = str(col).lower()
            if "tên trường" in c_lower or "trường" in c_lower or "school" in c_lower:
                name_col = col
                break
                
    if name_col is None:
        # Just use Unnamed: 2 or index 2 which is common in our files
        if len(df.columns) > 2:
            name_col = df.columns[2]
        else:
            name_col = df.columns[0]
            
    print(f"\nMatching {name} using column: '{name_col}'")
    
    matched = 0
    unmatched_names = []
    
    for idx, row in df.iterrows():
        raw_name = row[name_col]
        if pd.isna(raw_name) or not isinstance(raw_name, str) or raw_name.strip() == "" or "TÊN TRƯỜNG" in raw_name or "TRƯỜNG" in raw_name:
            continue
            
        norm_excel = normalize_name(raw_name)
        if not norm_excel:
            continue
            
        found = False
        for u in universities:
            norm_vi = normalize_name(u["name_vi"])
            norm_en = normalize_name(u["name_en"])
            norm_ko = normalize_name(u["name_ko"])
            
            if norm_excel == norm_vi or norm_excel == norm_en or norm_excel == norm_ko:
                found = True
                break
            # substring matching
            if norm_excel in norm_vi or norm_vi in norm_excel:
                found = True
                break
                
        if found:
            matched += 1
        else:
            unmatched_names.append(raw_name.replace('\n', ' '))
            
    print(f"Matched: {matched} schools. Unmatched: {len(unmatched_names)}")
    if unmatched_names:
        print("Sample unmatched names:", unmatched_names[:10])
